name: Deploy atmadeva-retreats.com

on:
  push:
    branches:
      - main  # Заменить на свою основную ветку, если другая

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Получаем код репозитория
        uses: actions/checkout@v4

      - name: Копируем файлы на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/atmadeva"

      - name: Выполняем деплой через SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/atmadeva
            git pull origin main
            npm install
            npm run build
            pm2 restart atmadeva || pm2 start npm --name "atmadeva" -- start
